export const resData = [
  {
    resId: 1,
    resName: "Bakery World",
    cuisines: ["Pastry", "Desserts", "Bakery"],
    rating: "3.2",
    deliveryTime: "30-40",
    imgId: "mt2aggiscfl3yviatwng",
  },
  {
    resId: 2,
    resName: "Adil Hotel",
    cuisines: ["Biryani", "North Indian", "Mughlai"],
    rating: "4.2",
    deliveryTime: "30-40",
    imgId: "gp1ityra6utvzqn6ghnv",
  },
  {
    resId: 3,
    resName: "McDonald's",
    cuisines: ["Burger", "American"],
    rating: "4.2",
    deliveryTime: "20-30",
    imgId: "enj3srsnhbltbom2ovvh",
  },
  {
    resId: 4,
    resName: "Bakery World",
    cuisines: ["Pastry", "Desserts", "Bakery"],
    rating: "3.2",
    deliveryTime: "30-40",
    imgId: "mt2aggiscfl3yviatwng",
  },
  {
    resId: 5,
    resName: "Adil Hotel",
    cuisines: ["Biryani", "North Indian", "Mughlai"],
    rating: "4.2",
    deliveryTime: "30-40",
    imgId: "gp1ityra6utvzqn6ghnv",
  },
  {
    resId: 6,
    resName: "McDonald's",
    cuisines: ["Burger", "American"],
    rating: "4.2",
    deliveryTime: "20-30",
    imgId: "enj3srsnhbltbom2ovvh",
  },
  {
    resId: 7,
    resName: "Bakery World",
    cuisines: ["Pastry", "Desserts", "Bakery"],
    rating: "3.2",
    deliveryTime: "30-40",
    imgId: "mt2aggiscfl3yviatwng",
  },
  {
    resId: 8,
    resName: "Adil Hotel",
    cuisines: ["Biryani", "North Indian", "Mughlai"],
    rating: "4.2",
    deliveryTime: "30-40",
    imgId: "gp1ityra6utvzqn6ghnv",
  },
  {
    resId: 9,
    resName: "McDonald's",
    cuisines: ["Burger", "American"],
    rating: "4.2",
    deliveryTime: "20-30",
    imgId: "enj3srsnhbltbom2ovvh",
  },
  {
    resId: 10,
    resName: "Bakery World",
    cuisines: ["Pastry", "Desserts", "Bakery"],
    rating: "3.2",
    deliveryTime: "30-40",
    imgId: "mt2aggiscfl3yviatwng",
  },
  {
    resId: 11,
    resName: "Adil Hotel",
    cuisines: ["Biryani", "North Indian", "Mughlai"],
    rating: "4.2",
    deliveryTime: "30-40",
    imgId: "gp1ityra6utvzqn6ghnv",
  },
  {
    resId: 12,
    resName: "McDonald's",
    cuisines: ["Burger", "American"],
    rating: "4.2",
    deliveryTime: "20-30",
    imgId: "enj3srsnhbltbom2ovvh",
  },
];
